### ISSUE TITLE
💡 [REQUEST] - **NEW PAGE** (Mobile App Download)

### ISSUE THREAD

**Issue by heartless9** [fgacyc/website#14]
### Summary

Implement **Mobile App Download** section

### Basic Example

https://www.figma.com/file/h1CtGXZD7aRr9y13nhEwQN/FGACYC-Website?type=design&node-id=0-1&mode=design&t=lvlQ05i4aDbYmGAb-0

![image](https://github.com/fgacyc/website/assets/141703204/a740880d-53de-475a-8b23-d7bb4fa9bb8a)

### General things to do

- [x] Page Display
- [x] Page Navigation

**Comment by whyiwant** [comment]
Waiting for app link

**Comment by heartless9** [comment]
> Waiting for app link

next phase
